=== wilkyo/projet-aar-geozouwil/SoccerTournamentEJB/ejbModule/META-INF/data/equipes.dtd
<?xml version="1.0" encoding="UTF-8" ?>
<!ELEMENT Equipes (Equipe*)>

<!ELEMENT Equipe (Joueur+)>
	<!ATTLIST Equipe nom CDATA #REQUIRED>
	<!ATTLIST Equipe nomRepresentant CDATA #REQUIRED>
	<!ATTLIST Equipe prenomRepresentant CDATA #REQUIRED>

<!ELEMENT Joueur (#PCDATA)>
	<!ATTLIST Joueur nom CDATA #REQUIRED>
	<!ATTLIST Joueur prenom CDATA #REQUIRED>
	<!ATTLIST Joueur numero CDATA #IMPLIED>

=== wilkyo/projet-aar-geozouwil/SoccerTournamentEJB/ejbModule/META-INF/data/equipes.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE equipes SYSTEM "equipes.dtd">
<Equipes>
	<Equipe nom="Paris Saint-Germain" nomRepresentant="Blanc"
		prenomRepresentant="Laurent">
		<Joueur nom="Douchez" prenom="Nicolas" numero="1" />
		<Joueur nom="Silva" prenom="Thiago" numero="2" />
		<Joueur nom="" prenom="Marquinhos" numero="5" />
		<Joueur nom="Ménez" prenom="Jérémy" numero="7" />
		<Joueur nom="Motta" prenom="Thiago" numero="8" />
		<Joueur nom="Cavani" prenom="Edinson" numero="9" />
		<Joueur nom="Ibrahimovic" prenom="Zlatan" numero="10" />
		<Joueur nom="Matuidi" prenom="Blaise" numero="14" />
		<Joueur nom="Jallet" prenom="Christophe" numero="26" />
		<Joueur nom="" prenom="Lucas" numero="29" />
		<Joueur nom="Sirigu" prenom="Salvatore" numero="30" />
	</Equipe>
	<Equipe nom="Olympique de Marseille" nomRepresentant="Baup"
		prenomRepresentant="Élie">
		<Joueur nom="Gennaro" prenom="Bracigliano" numero="1" />
		<Joueur nom="Cheyrou" prenom="Benoît" numero="7" />
		<Joueur nom="Ayew" prenom="André" numero="10" />
		<Joueur nom="Ayew" prenom="Jordan" numero="11" />
		<Joueur nom="Thauvin" prenom="Florian" numero="14" />
		<Joueur nom="Morel" prenom="Jérémy" numero="15" />
		<Joueur nom="Payet" prenom="Dimitri" numero="17" />
		<Joueur nom="Diawara" prenom="Souleymane" numero="21" />
		<Joueur nom="Fanni" prenom="Rod" numero="24" />
		<Joueur nom="Valbuena" prenom="Mathieu" numero="28" />
		<Joueur nom="Mandanda" prenom="Steve" numero="30" />
	</Equipe>
	<Equipe nom="Saint-Etienne" nomRepresentant="Galtier"
		prenomRepresentant="Christophe">
		<Joueur nom="Zouma" prenom="Kurt" numero="4" />
		<Joueur nom="Clément" prenom="Jérémy" numero="6" />
		<Joueur nom="Saadi" prenom="Idriss" numero="8" />
		<Joueur nom="" prenom="Brandao" numero="9" />
		<Joueur nom="Cohade" prenom="Renaud" numero="10" />
		<Joueur nom="Mollo" prenom="Yohan" numero="11" />
		<Joueur nom="Ruffier" prenom="Stéphane" numero="16" />
		<Joueur nom="Brison" prenom="Jonathan" numero="20" />
		<Joueur nom="Hamouma" prenom="Romain" numero="21" />
		<Joueur nom="Perrin" prenom="Loic" numero="24" />
		<Joueur nom="Clerc" prenom="François" numero="29" />
	</Equipe>
	<Equipe nom="Olympique Lyonnais" nomRepresentant="Garde"
		prenomRepresentant="Rémi">
		<Joueur nom="Vercoutre" prenom="Rémy" numero="1" />
		<Joueur nom="Koné" prenom="Bakary" numero="4" />
		<Joueur nom="Bisevac" prenom="Milan" numero="5" />
		<Joueur nom="Grenier" prenom="Clément" numero="7" />
		<Joueur nom="Gourcuff" prenom="Yoann" numero="8" />
		<Joueur nom="Lacazette" prenom="Alexandre" numero="10" />
		<Joueur nom="Lopes" prenom="Anthony" numero="16" />
		<Joueur nom="Malbranque" prenom="Steed" numero="17" />
		<Joueur nom="Gomis" prenom="Bafetimbi" numero="18" />
		<Joueur nom="Briand" prenom="Jimmy" numero="19" />
		<Joueur nom="Gonalons" prenom="Maxime" numero="21" />
	</Equipe>
	<Equipe nom="Pure Info" nomRepresentant="François"
		prenomRepresentant="Willy">
		<Joueur nom="Benkabbou" prenom="Mohammed Hamza" numero="1" />
		<Joueur nom="Rabarijaona" prenom="Zo" numero="2" />
		<Joueur nom="Morosi" prenom="Jérémy" numero="3" />
		<Joueur nom="François" prenom="Willy" numero="5" />
		<Joueur nom="Chauvin" prenom="Rémi" numero="7" />
		<Joueur nom="Robillard" prenom="Simon" numero="9" />
		<Joueur nom="Vogel" prenom="Jimmy" numero="10" />
		<Joueur nom="Dexmier" prenom="Yoann" numero="14" />
		<Joueur nom="Bourgeois" prenom="Kévin" numero="15" />
		<Joueur nom="Poirrier" prenom="Jérôme" numero="16" />
		<Joueur nom="Nouira" prenom="Nicolas" numero="17" />
		<Joueur nom="Peres" prenom="Jean-Christophe" numero="18" />
	</Equipe>
	<Equipe nom="From IUT" nomRepresentant="Masson"
		prenomRepresentant="Alexandre">
		<Joueur nom="Masson" prenom="Alexandre" numero="1" />
		<Joueur nom="Champigny" prenom="Florent" numero="2" />
		<Joueur nom="De Jesus Ferreira" prenom="Kevin" numero="3" />
		<Joueur nom="Mialon" prenom="Julien" numero="6" />
		<Joueur nom="Perrin" prenom="Jean-Baptiste" numero="7" />
		<Joueur nom="Leguy" prenom="Antoine" numero="9" />
		<Joueur nom="Monedière" prenom="Tristan" numero="11" />
		<Joueur nom="Boyer" prenom="Benoit" numero="13" />
		<Joueur nom="Bordier" prenom="Christophe" numero="14" />
		<Joueur nom="Fontorbe" prenom="Jordan" numero="17" />
		<Joueur nom="Savoure" prenom="Benjamin" numero="18" />
		<Joueur nom="Rousseau" prenom="Léo" numero="19" />
		<Joueur nom="Besson" prenom="Tom" numero="22" />
	</Equipe>
	<Equipe nom="Teacher Power" nomRepresentant="Ed-dbali"
		prenomRepresentant="Ali">
		<Joueur nom="Exbrayat" prenom="Matthieu" numero="1" />
		<Joueur nom="Moal" prenom="Frédéric" numero="2" />
		<Joueur nom="Couvreur" prenom="Jean-Michel" numero="3" />
		<Joueur nom="Boichut" prenom="Yohan" numero="6" />
		<Joueur nom="Coullon" prenom="Hélène" numero="7" />
		<Joueur nom="Dabrowski" prenom="Frédéric" numero="8" />
		<Joueur nom="Robert" prenom="Sophie" numero="9" />
		<Joueur nom="Ed-dbali" prenom="Ali" numero="12" />
		<Joueur nom="Todinca" prenom="Ioan" numero="13" />
		<Joueur nom="Djelloul" prenom="Khalil" numero="15" />
		<Joueur nom="Liedloff" prenom="Mathieu" numero="17" />
		<Joueur nom="Dao" prenom="Thi Bich Hanh" numero="19" />
		<Joueur nom="Loulergue" prenom="Frédéric" numero="22" />
	</Equipe>
	<!---->
	<Equipe nom="MIAGE's spirit" nomRepresentant="Cointepas"
		prenomRepresentant="Antoine">
		<Joueur nom="Cointepas" prenom="Antoine" numero="1" />
		<Joueur nom="Leloup" prenom="Nicolas" numero="2" />
		<Joueur nom="Rousseau" prenom="Benjamin" numero="3" />
		<Joueur nom="Crochet" prenom="Geoffrey" numero="5" />
		<Joueur nom="Fikri" prenom="Ikbal" numero="12" />
		<Joueur nom="Abas" prenom="Tarik" numero="13" />
		<Joueur nom="Lambarraa" prenom="Rachid" numero="15" />
		<Joueur nom="Blivet" prenom="Thibault" numero="17" />
		<Joueur nom="Château" prenom="Julien" numero="17" />
		<Joueur nom="San" prenom="Lucas" numero="18" />
		<Joueur nom="Barruet" prenom="Corentin" numero="19" />
	</Equipe>
	<!---->
</Equipes>

=== wilkyo/projet-aar-geozouwil/trunk/SoccerTournamentEJB/ejbModule/META-INF/data/equipes.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE equipes SYSTEM "equipes.dtd">
<Equipes>
	<Equipe nom="Paris Saint-Germain" nomRepresentant="Blanc"
		prenomRepresentant="Laurent">
		<Joueur nom="Douchez" prenom="Nicolas" numero="1" />
		<Joueur nom="Silva" prenom="Thiago" numero="2" />
		<Joueur nom="" prenom="Marquinhos" numero="5" />
		<Joueur nom="Ménez" prenom="Jérémy" numero="7" />
		<Joueur nom="Motta" prenom="Thiago" numero="8" />
		<Joueur nom="Cavani" prenom="Edinson" numero="9" />
		<Joueur nom="Ibrahimovic" prenom="Zlatan" numero="10" />
		<Joueur nom="Matuidi" prenom="Blaise" numero="14" />
		<Joueur nom="Jallet" prenom="Christophe" numero="26" />
		<Joueur nom="" prenom="Lucas" numero="29" />
		<Joueur nom="Sirigu" prenom="Salvatore" numero="30" />
	</Equipe>
	<Equipe nom="Olympique de Marseille" nomRepresentant="Baup"
		prenomRepresentant="Élie">
		<Joueur nom="Gennaro" prenom="Bracigliano" numero="1" />
		<Joueur nom="Cheyrou" prenom="Benoît" numero="7" />
		<Joueur nom="Ayew" prenom="André" numero="10" />
		<Joueur nom="Ayew" prenom="Jordan" numero="11" />
		<Joueur nom="Thauvin" prenom="Florian" numero="14" />
		<Joueur nom="Morel" prenom="Jérémy" numero="15" />
		<Joueur nom="Payet" prenom="Dimitri" numero="17" />
		<Joueur nom="Diawara" prenom="Souleymane" numero="21" />
		<Joueur nom="Fanni" prenom="Rod" numero="24" />
		<Joueur nom="Valbuena" prenom="Mathieu" numero="28" />
		<Joueur nom="Mandanda" prenom="Steve" numero="30" />
	</Equipe>
	<Equipe nom="Saint-Etienne" nomRepresentant="Galtier"
		prenomRepresentant="Christophe">
		<Joueur nom="Zouma" prenom="Kurt" numero="4" />
		<Joueur nom="Clément" prenom="Jérémy" numero="6" />
		<Joueur nom="Saadi" prenom="Idriss" numero="8" />
		<Joueur nom="" prenom="Brandao" numero="9" />
		<Joueur nom="Cohade" prenom="Renaud" numero="10" />
		<Joueur nom="Mollo" prenom="Yohan" numero="11" />
		<Joueur nom="Ruffier" prenom="Stéphane" numero="16" />
		<Joueur nom="Brison" prenom="Jonathan" numero="20" />
		<Joueur nom="Hamouma" prenom="Romain" numero="21" />
		<Joueur nom="Perrin" prenom="Loic" numero="24" />
		<Joueur nom="Clerc" prenom="François" numero="29" />
	</Equipe>
	<Equipe nom="Olympique Lyonnais" nomRepresentant="Garde"
		prenomRepresentant="Rémi">
		<Joueur nom="Vercoutre" prenom="Rémy" numero="1" />
		<Joueur nom="Koné" prenom="Bakary" numero="4" />
		<Joueur nom="Bisevac" prenom="Milan" numero="5" />
		<Joueur nom="Grenier" prenom="Clément" numero="7" />
		<Joueur nom="Gourcuff" prenom="Yoann" numero="8" />
		<Joueur nom="Lacazette" prenom="Alexandre" numero="10" />
		<Joueur nom="Lopes" prenom="Anthony" numero="16" />
		<Joueur nom="Malbranque" prenom="Steed" numero="17" />
		<Joueur nom="Gomis" prenom="Bafetimbi" numero="18" />
		<Joueur nom="Briand" prenom="Jimmy" numero="19" />
		<Joueur nom="Gonalons" prenom="Maxime" numero="21" />
	</Equipe>
</Equipes>
